# -*- coding: utf-8 -*-

fields = [
	'frame.time_epoch',
	'frame.len',
	'eth.src',
	'eth.dst',
	'eth.type',
	'ip.version',
	'ip.src',
	'ip.dst',
	'ip.proto',
	'ipv6.src',
	'ipv6.dst',
	'ipv6.nxt',
	'tcp.srcport',
	'tcp.dstport',
	'tcp.flags.urg',
	'tcp.flags.ack',
	'tcp.flags.push',
	'tcp.flags.reset',
	'tcp.flags.syn',
	'tcp.flags.fin',
	'tcp.seq',
	'tcp.ack',
# comment out 2017-03-04
#	'expert.message',
#	'expert.severity',
#	'expert.group',
	'http.host',
	'http.request.uri',
	'http.request.method',
	'http.request.version',
	'http.response.code',
	'http.response.phrase',
	'http.content_type',
	'http.content_length',
	'http.user_agent',
	'http.server',
	'http.connection',
	'ssl',
	'udp.srcport',
	'udp.dstport', 
	'dns.id',
	'dns.qry.type',
	'dns.qry.name',
# dns.resp.type → dns.resp.name
	'dns.resp.name',
# comment out 2017-03-04
#	'dns.resp.addr',
# added 2017-03-07
	'dns.a',
	'wlccp',
	'arp.opcode',
	'arp.isgratuitous',
	'bootp.dhcp',
	'bootp.option.type',
	'bootp.option.value',
	'icmp.type',
	'icmp.code',
	'icmpv6.type',
	'icmpv6.code'
	]


